"use client";

import { useEffect, useState } from "react";
import type { Locale } from "../language-toggle";

type Credential = { id:string; name:string; tokenPrefix:string; scopes:string[]; status:string; expiresAt:string|null; lastUsedAt:string|null; createdAt:string };
type Labels = Record<"eyebrow"|"title"|"description"|"name"|"placeholder"|"read"|"context"|"conversation"|"plan"|"create"|"creating"|"active"|"empty"|"revoke"|"secret"|"copyToken"|"copyConfig"|"copied"|"saved"|"boundary",string>;
const labels:Record<Locale,Labels>={
  en:{eyebrow:"CONNECT OTHER AI AGENTS",title:"Use Carmelita from your own agent.",description:"Create a scoped Testnet credential for Codex, Claude or any Remote MCP client.",name:"Credential name",placeholder:"My Codex workspace",read:"Read capabilities and owned plans",context:"Share profile, wallets and connections",conversation:"Share recent conversation history",plan:"Prepare safe action plans",create:"Create Testnet credential",creating:"Creating...",active:"Active credentials",empty:"No external agents connected yet.",revoke:"Revoke",secret:"Copy this token now. It will never be shown again.",copyToken:"Copy token",copyConfig:"Copy Codex config",copied:"Copied",saved:"I saved it",boundary:"No wallet key is shared. External agents cannot sign or move funds; approval remains inside Carmelita with Privy."},
  es:{eyebrow:"CONECTA OTROS AGENTES DE IA",title:"Usa Carmelita desde tu propio agente.",description:"Crea una credencial limitada de Testnet para Codex, Claude o cualquier cliente Remote MCP.",name:"Nombre de la credencial",placeholder:"Mi espacio de Codex",read:"Leer capacidades y planes propios",context:"Compartir perfil, wallets y conexiones",conversation:"Compartir historial reciente de conversaciones",plan:"Preparar planes de accion seguros",create:"Crear credencial Testnet",creating:"Creando...",active:"Credenciales activas",empty:"Todavia no hay agentes externos conectados.",revoke:"Revocar",secret:"Copia este token ahora. No volvera a mostrarse.",copyToken:"Copiar token",copyConfig:"Copiar configuracion Codex",copied:"Copiado",saved:"Ya lo guarde",boundary:"No se comparte ninguna clave de wallet. Los agentes externos no pueden firmar ni mover fondos; la aprobacion permanece en Carmelita con Privy."},
  pt:{eyebrow:"CONECTE OUTROS AGENTES DE IA",title:"Use Carmelita a partir do seu proprio agente.",description:"Crie uma credencial limitada de Testnet para Codex, Claude ou qualquer cliente Remote MCP.",name:"Nome da credencial",placeholder:"Meu workspace Codex",read:"Ler capacidades e planos proprios",context:"Compartilhar perfil, wallets e conexoes",conversation:"Compartilhar historico recente de conversas",plan:"Preparar planos de acao seguros",create:"Criar credencial Testnet",creating:"Criando...",active:"Credenciais ativas",empty:"Ainda nao existem agentes externos conectados.",revoke:"Revogar",secret:"Copie este token agora. Ele nao sera mostrado novamente.",copyToken:"Copiar token",copyConfig:"Copiar configuracao Codex",copied:"Copiado",saved:"Ja salvei",boundary:"Nenhuma chave da wallet e compartilhada. Agentes externos nao podem assinar ou mover fundos; a aprovacao permanece no Carmelita com Privy."}
};
function mcpEndpoint(){return `${window.location.origin}/api/mcp/agent`}

export default function AgentExternalAccess({locale,getAccessToken}:{locale:Locale;getAccessToken:()=>Promise<string|null>}){
  const t=labels[locale]; const [credentials,setCredentials]=useState<Credential[]>([]); const [name,setName]=useState(""); const [plan,setPlan]=useState(false); const [context,setContext]=useState(false); const [conversation,setConversation]=useState(false); const [rawToken,setRawToken]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [copied,setCopied]=useState<string|null>(null);
  async function call(url:string,init?:RequestInit){const token=await getAccessToken();if(!token)throw new Error("privy_access_token_unavailable");return fetch(url,{...init,headers:{...init?.headers,Authorization:`Bearer ${token}`,"Content-Type":"application/json"}})}
  async function load(){try{const response=await call("/api/agent/mcp-tokens");const body=await response.json();if(!response.ok)throw new Error(body.error);setCredentials((body.credentials??[]).filter((item:Credential)=>item.status==="active"))}catch(caught){setError(caught instanceof Error?caught.message:"mcp_tokens_load_failed")}}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[]);
  async function create(event:React.FormEvent){event.preventDefault();setBusy(true);setError(null);try{const scopes=["agent:read",...(plan?["agent:plan"]:[]),...(context?["agent:context"]:[]),...(conversation?["agent:conversation"]:[])];const response=await call("/api/agent/mcp-tokens",{method:"POST",body:JSON.stringify({name:name.trim()||"External agent",scopes,expiresInDays:30})});const body=await response.json();if(!response.ok)throw new Error(body.error);setRawToken(body.token);setName("");await load()}catch(caught){setError(caught instanceof Error?caught.message:"mcp_token_create_failed")}finally{setBusy(false)}}
  async function revoke(tokenId:string){setError(null);try{const response=await call(`/api/agent/mcp-tokens/${encodeURIComponent(tokenId)}`,{method:"DELETE"});const body=await response.json();if(!response.ok)throw new Error(body.error);await load()}catch(caught){setError(caught instanceof Error?caught.message:"mcp_token_revoke_failed")}}
  const config=()=>`[mcp_servers.carmelita]\nurl = "${mcpEndpoint()}"\nbearer_token_env_var = "CARMELITA_MCP_TOKEN"\ndefault_tools_approval_mode = "writes"`;
  async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);window.setTimeout(()=>setCopied(null),1400)}
  return <section className="agent-external-access"><header><div><p className="eyebrow">{t.eyebrow}</p><h2>{t.title}</h2><p>{t.description}</p></div><b>REMOTE MCP · TESTNET</b></header><div className="agent-external-grid"><form onSubmit={create}><label>{t.name}<input value={name} onChange={event=>setName(event.target.value)} placeholder={t.placeholder} maxLength={80}/></label><label className="agent-scope"><input type="checkbox" checked readOnly/><span>{t.read}</span></label><label className="agent-scope"><input type="checkbox" checked={context} onChange={event=>setContext(event.target.checked)}/><span>{t.context}</span></label><label className="agent-scope"><input type="checkbox" checked={conversation} onChange={event=>setConversation(event.target.checked)}/><span>{t.conversation}</span></label><label className="agent-scope"><input type="checkbox" checked={plan} onChange={event=>setPlan(event.target.checked)}/><span>{t.plan}</span></label><button disabled={busy}>{busy?t.creating:t.create}</button></form><div className="agent-token-list"><h3>{t.active}</h3>{credentials.length===0&&<p>{t.empty}</p>}{credentials.map(item=><article key={item.id}><div><strong>{item.name}</strong><code>{item.tokenPrefix}...</code><small>{item.scopes.join(" · ")}</small></div><button type="button" onClick={()=>void revoke(item.id)}>{t.revoke}</button></article>)}</div></div>{rawToken&&<aside className="agent-token-secret"><strong>{t.secret}</strong><code>{rawToken}</code><div><button onClick={()=>void copy(rawToken,"token")}>{copied==="token"?t.copied:t.copyToken}</button><button onClick={()=>void copy(config(),"config")}>{copied==="config"?t.copied:t.copyConfig}</button><button className="secondary" onClick={()=>setRawToken(null)}>{t.saved}</button></div></aside>}{error&&<p className="agent-external-error">{error}</p>}<footer>{t.boundary}</footer></section>;
}
