export const stellarPaymentCopy = {
  en: {
    fullContent: "View the complete delivered content", historicalPreview: "View the saved historical excerpt",
    payment: "Payment", delivery: "Delivery", expires: "Approval expires", expired: "Approval expired. A new review is required before signing.", query: "Check payment status", prepareAgain: "Prepare a new approval", method: "Request method", fees: "Transaction fees", sponsored: "Sponsored", unavailableBalance: "Balance unavailable",
    states: { pending: "Pending", confirmed: "Confirmed", uncertain: "Uncertain — check status", received: "Received and verified" },
    notices: { requirements: "The required USDC trustline or balance is missing. This flow does not create trustlines or add funds. Complete those steps separately with explicit approval.", existing: "An existing payment needs attention. Check its status to recover the same operation.", changed: "The payment conditions changed or the approval expired. Review the updated information before signing.", expired: "The approval expired before submission. Review a new approval to continue.", uncertain: "The submission result is uncertain. Keep this payment and check its status; do not start another payment.", verified: "Payment and delivery are independently verified.", replayed: "The same verified payment and receipt were returned without a new settlement.", signingCancelled: "Signing was not completed. No payment request was sent by this action.", unavailable: "The payment could not be prepared. No wallet funding was requested.", lookupFailed: "The original payment could not be retrieved. Its reference was preserved; retry checking its status.", restored: "The original payment was restored. Its payment and delivery states are shown separately.", none: "No existing payment was found.", x402_restore_unavailable: "An existing payment could not be restored. Check its status before starting another operation." },
  },
  es: {
    fullContent: "Ver el contenido completo recibido", historicalPreview: "Ver el extracto histórico guardado",
    payment: "Pago", delivery: "Entrega", expires: "Vencimiento de la aprobación", expired: "La aprobación venció. Se requiere una nueva revisión antes de firmar.", query: "Consultar estado del pago", prepareAgain: "Preparar nueva aprobación", method: "Método de la petición", fees: "Comisiones de la transacción", sponsored: "Patrocinadas", unavailableBalance: "Saldo no disponible",
    states: { pending: "Pendiente", confirmed: "Confirmado", uncertain: "Incierto — consultar estado", received: "Recibida y verificada" },
    notices: { requirements: "Falta la trustline o el saldo del USDC requerido. Este flujo no crea trustlines ni agrega fondos. Completa esos pasos por separado con aprobación explícita.", existing: "Hay un pago existente que requiere atención. Consulta su estado para recuperar la misma operación.", changed: "Las condiciones cambiaron o la aprobación venció. Revisa la información actualizada antes de firmar.", expired: "La aprobación venció antes del envío. Revisa una nueva aprobación para continuar.", uncertain: "El resultado del envío es incierto. Conserva este pago y consulta su estado; no inicies otro pago.", verified: "El pago y la entrega están verificados por separado.", replayed: "Se devolvieron el mismo pago verificado y su recibo, sin una nueva liquidación.", signingCancelled: "La firma no se completó. Esta acción no envió una solicitud de pago.", unavailable: "No se pudo preparar el pago. No se solicitó financiación de la wallet.", lookupFailed: "No se pudo recuperar el pago original. Su referencia se conservó; reintenta la consulta de estado.", restored: "Se recuperó el pago original. El estado del pago y de la entrega se muestran por separado.", none: "No se encontró un pago existente.", x402_restore_unavailable: "No se pudo recuperar un pago existente. Consulta su estado antes de iniciar otra operación." },
  },
  pt: {
    fullContent: "Ver o conteúdo completo recebido", historicalPreview: "Ver o trecho histórico salvo",
    payment: "Pagamento", delivery: "Entrega", expires: "Vencimento da aprovação", expired: "A aprovação venceu. Uma nova revisão é necessária antes de assinar.", query: "Consultar status do pagamento", prepareAgain: "Preparar nova aprovação", method: "Método da solicitação", fees: "Taxas da transação", sponsored: "Patrocinadas", unavailableBalance: "Saldo indisponível",
    states: { pending: "Pendente", confirmed: "Confirmado", uncertain: "Incerto — consultar status", received: "Recebida e verificada" },
    notices: { requirements: "Falta a trustline ou o saldo do USDC necessário. Este fluxo não cria trustlines nem adiciona fundos. Conclua essas etapas separadamente com aprovação explícita.", existing: "Há um pagamento existente que requer atenção. Consulte seu status para recuperar a mesma operação.", changed: "As condições mudaram ou a aprovação venceu. Revise as informações atualizadas antes de assinar.", expired: "A aprovação venceu antes do envio. Revise uma nova aprovação para continuar.", uncertain: "O resultado do envio é incerto. Preserve este pagamento e consulte seu status; não inicie outro pagamento.", verified: "O pagamento e a entrega estão verificados separadamente.", replayed: "O mesmo pagamento verificado e seu recibo foram retornados sem uma nova liquidação.", signingCancelled: "A assinatura não foi concluída. Esta ação não enviou uma solicitação de pagamento.", unavailable: "Não foi possível preparar o pagamento. Nenhum financiamento da wallet foi solicitado.", lookupFailed: "Não foi possível recuperar o pagamento original. Sua referência foi preservada; tente consultar o status novamente.", restored: "O pagamento original foi recuperado. Os estados do pagamento e da entrega são mostrados separadamente.", none: "Nenhum pagamento existente foi encontrado.", x402_restore_unavailable: "Não foi possível recuperar um pagamento existente. Consulte seu status antes de iniciar outra operação." },
  },
} as const;
