export const workspaceCopy = {
  es: {
    wallets: "Billeteras", functions: "Funciones", account: "Cuenta", developers: "Desarrolladores", close: "Cerrar",
    preparing: "Estamos preparando tus billeteras…", failed: "No pudimos cargar tus billeteras.", retry: "Reintentar", partial: "Algunas billeteras aún no están disponibles. Puedes consultar las que ya están registradas.",
    signIn: "Ingresar", welcome: "Habla con Carmelita", welcomeText: "Ingresa con Privy para consultar tus billeteras y explorar funciones en Testnet.", help: "Ayuda", registered: "Registrada", pending: "No registrada", network: "Red", address: "Dirección", status: "Estado del registro", explorer: "Explorador", balance: "Consultar saldos", registryNote: "El registro no confirma saldo ni activación en la red. Las tres redes EVM comparten una dirección.",
    consultations: "Consultas", walletPrompt: "Muéstrame mis billeteras con red, dirección, estado del registro y explorador.", price: "Precios de mercado", pricePrompt: "Consulta el precio de XLM e indica la fuente y la fecha.", capabilities: "Qué puedo hacer", capabilitiesPrompt: "¿Qué funciones están disponibles en Carmelita y cuáles puedo consultar desde ChatGPT?", fill: "Usar ejemplo", exampleNote: "Los ejemplos rellenan el mensaje. Tú decides cuándo enviarlo.",
    marketNote: "El proveedor efectivo se indica en cada respuesta.", connections: "Conexiones", chatgptNote: "ChatGPT es opcional: consulta contexto, conversaciones y catálogos; permite preparar planes. Requiere una conexión autorizada.", notionNote: "Notion: búsqueda disponible al conectar tu cuenta.", advanced: "Pruebas avanzadas", advancedNote: "Las capacidades de prueba y las planificadas se distinguen en el catálogo. Cada operación financiera requiere autorización aparte.", travel: "Buscar hoteles con Travala", travelNote: "Función de prueba: búsqueda o aviso de indisponibilidad. No reserva ni paga.", activity: "Actividad", memory: "Memoria", empty: "Todavía no hay actividad.", signout: "Cerrar sesión", identity: "Identidad", commands: "Comandos de consulta", developerNote: "Los comandos se escriben en el chat. WebMCP sigue activo aunque este panel esté cerrado.", credentials: "Credenciales y acceso avanzado", diagnostics: "Diagnóstico WebMCP", where: "Destino", checkIn: "Entrada", checkOut: "Salida", guests: "Personas", maxPrice: "Máximo USD/noche", search: "Buscar hoteles", searching: "Buscando…", travelError: "La búsqueda no está disponible. Puedes reintentar.", options: "opciones encontradas", night: "noche", guide: "Guía",
  },
  en: {
    wallets: "Wallets", functions: "Functions", account: "Account", developers: "Developers", close: "Close",
    preparing: "Preparing your wallets…", failed: "We could not load your wallets.", retry: "Retry", partial: "Some wallets are not available yet. You can query those already registered.",
    signIn: "Sign in", welcome: "Talk to Carmelita", welcomeText: "Sign in with Privy to query your wallets and explore Testnet functions.", help: "Help", registered: "Registered", pending: "Not registered", network: "Network", address: "Address", status: "Registry status", explorer: "Explorer", balance: "Query balances", registryNote: "Registration does not confirm a balance or on-chain activation. The three EVM networks share one address.",
    consultations: "Queries", walletPrompt: "Show my wallets with network, address, registry status and explorer.", price: "Market prices", pricePrompt: "Query the XLM price and include the source and date.", capabilities: "What can I do", capabilitiesPrompt: "Which functions are available in Carmelita and which can I query from ChatGPT?", fill: "Use example", exampleNote: "Examples fill your message. You decide when to send it.", marketNote: "Each response identifies the actual provider.", connections: "Connections", chatgptNote: "ChatGPT is optional: query context, conversations and catalogs, and prepare plans. An authorized connection is required.", notionNote: "Notion: search is available after connecting your account.", advanced: "Advanced tests", advancedNote: "The catalog distinguishes test and planned capabilities. Each financial operation requires separate authorization.", travel: "Search hotels with Travala", travelNote: "Test function: search or an availability notice. No booking or payment.", activity: "Activity", memory: "Memory", empty: "No activity yet.", signout: "Sign out", identity: "Identity", commands: "Query commands", developerNote: "Type commands in chat. WebMCP remains active when this panel is closed.", credentials: "Credentials and advanced access", diagnostics: "WebMCP diagnostics", where: "Destination", checkIn: "Check-in", checkOut: "Check-out", guests: "Guests", maxPrice: "Max USD/night", search: "Search hotels", searching: "Searching…", travelError: "Search is unavailable. You can retry.", options: "options found", night: "night", guide: "Guide",
  },
  pt: {
    wallets: "Carteiras", functions: "Funções", account: "Conta", developers: "Desenvolvedores", close: "Fechar",
    preparing: "Preparando suas carteiras…", failed: "Não foi possível carregar suas carteiras.", retry: "Tentar novamente", partial: "Algumas carteiras ainda não estão disponíveis. Você pode consultar as já registradas.",
    signIn: "Entrar", welcome: "Converse com Carmelita", welcomeText: "Entre com Privy para consultar suas carteiras e explorar funções na Testnet.", help: "Ajuda", registered: "Registrada", pending: "Não registrada", network: "Rede", address: "Endereço", status: "Estado do registro", explorer: "Explorador", balance: "Consultar saldos", registryNote: "O registro não confirma saldo nem ativação na rede. As três redes EVM compartilham um endereço.",
    consultations: "Consultas", walletPrompt: "Mostre minhas carteiras com rede, endereço, estado do registro e explorador.", price: "Preços de mercado", pricePrompt: "Consulte o preço de XLM e indique a fonte e a data.", capabilities: "O que posso fazer", capabilitiesPrompt: "Quais funções estão disponíveis na Carmelita e quais posso consultar pelo ChatGPT?", fill: "Usar exemplo", exampleNote: "Os exemplos preenchem a mensagem. Você decide quando enviá-la.", marketNote: "Cada resposta indica o fornecedor efetivo.", connections: "Conexões", chatgptNote: "ChatGPT é opcional: consulta contexto, conversas e catálogos e prepara planos. Requer uma conexão autorizada.", notionNote: "Notion: busca disponível ao conectar sua conta.", advanced: "Testes avançados", advancedNote: "O catálogo distingue funções de teste e planejadas. Cada operação financeira exige autorização separada.", travel: "Buscar hotéis com Travala", travelNote: "Função de teste: busca ou aviso de indisponibilidade. Não reserva nem paga.", activity: "Atividade", memory: "Memória", empty: "Ainda não há atividade.", signout: "Sair", identity: "Identidade", commands: "Comandos de consulta", developerNote: "Digite comandos no chat. WebMCP continua ativo com este painel fechado.", credentials: "Credenciais e acesso avançado", diagnostics: "Diagnóstico WebMCP", where: "Destino", checkIn: "Entrada", checkOut: "Saída", guests: "Pessoas", maxPrice: "Máximo USD/noite", search: "Buscar hotéis", searching: "Buscando…", travelError: "A busca está indisponível. Você pode tentar novamente.", options: "opções encontradas", night: "noite", guide: "Guia",
  },
};
