export const voiceCopy = {
  es: {
    record: "Grabar voz", stop: "Detener grabación", cancel: "Cancelar", asking: "Esperando permiso de micrófono…", saving: "Conservando audio…", recording: "Grabando", saved: "Audio listo", recovered: "Audio recuperado de este navegador", interrupted: "Grabación interrumpida. Revisa el audio.",
    privacy: "Whisper local · sin API de pago. Primera descarga de unos 60 MB. El audio se procesa en este dispositivo.", transcribe: "Transcribir", downloading: "Descargando modelo", processing: "Transcribiendo en este dispositivo…", retry: "Reintentar transcripción", download: "Descargar audio", discard: "Descartar audio", use: "Usar texto", text: "Transcripción editable", review: "Revisa nombres, tickers y direcciones. El texto no se envía automáticamente.", inserted: "Texto añadido al borrador. Revisa y pulsa Enviar cuando decidas.", tooLong: "El mensaje supera 2000 caracteres. Acorta el texto; el audio se conserva.",
    storage: "No pudimos guardar el audio localmente. Descárgalo antes de cerrar esta pestaña.", denied: "Micrófono no disponible. Revisa el permiso del navegador y reintenta.", failed: "No pudimos transcribir. El audio se conserva para reintentar o descargar.", slow: "La transcripción tardó demasiado. Prueba un audio más breve; el original se conserva.", empty: "No detectamos voz clara. Escucha el audio antes de reintentar.", size: "El audio supera 2 minutos o 3 MB. Puedes descargarlo.", unsupported: "Este navegador no permite grabar y transcribir aquí. Puedes usar el dictado de tu teclado.", limit: "Máximo 2 minutos", microphone: "Micrófono", player: "Revisar audio grabado",
  },
  en: {
    record: "Record voice", stop: "Stop recording", cancel: "Cancel", asking: "Waiting for microphone permission…", saving: "Preserving audio…", recording: "Recording", saved: "Recorded audio", recovered: "Audio recovered from this browser", interrupted: "Recording interrupted. Review the audio.",
    privacy: "Local Whisper · no paid API. First download about 60 MB. Audio is processed on this device.", transcribe: "Transcribe", downloading: "Downloading model", processing: "Transcribing on this device…", retry: "Retry transcription", download: "Download audio", discard: "Discard audio", use: "Use text", text: "Editable transcript", review: "Check names, tickers and addresses. Text is never sent automatically.", inserted: "Text added to the draft. Review it and press Send when ready.", tooLong: "The message exceeds 2000 characters. Shorten it; audio is preserved.",
    storage: "We could not save audio locally. Download it before closing this tab.", denied: "Microphone unavailable. Check browser permission and retry.", failed: "Transcription failed. Audio is preserved for retry or download.", slow: "Transcription took too long. Try a shorter recording; the original is preserved.", empty: "No clear speech detected. Listen to the recording before retrying.", size: "Audio exceeds 2 minutes or 3 MB. You can download it.", unsupported: "This browser cannot record and transcribe here. You can use keyboard dictation.", limit: "Maximum 2 minutes", microphone: "Microphone", player: "Review recorded audio",
  },
  pt: {
    record: "Gravar voz", stop: "Parar gravação", cancel: "Cancelar", asking: "Aguardando permissão do microfone…", saving: "Preservando áudio…", recording: "Gravando", saved: "Áudio gravado", recovered: "Áudio recuperado deste navegador", interrupted: "Gravação interrompida. Revise o áudio.",
    privacy: "Whisper local · sem API paga. Primeiro download de cerca de 60 MB. O áudio é processado neste dispositivo.", transcribe: "Transcrever", downloading: "Baixando modelo", processing: "Transcrevendo neste dispositivo…", retry: "Tentar transcrição novamente", download: "Baixar áudio", discard: "Descartar áudio", use: "Usar texto", text: "Transcrição editável", review: "Revise nomes, tickers e endereços. O texto não é enviado automaticamente.", inserted: "Texto adicionado ao rascunho. Revise e clique em Enviar quando decidir.", tooLong: "A mensagem ultrapassa 2000 caracteres. Encurte-a; o áudio é preservado.",
    storage: "Não foi possível salvar o áudio localmente. Baixe-o antes de fechar esta aba.", denied: "Microfone indisponível. Verifique a permissão do navegador e tente novamente.", failed: "Não foi possível transcrever. O áudio é preservado para tentar novamente ou baixar.", slow: "A transcrição demorou demais. Tente um áudio mais curto; o original é preservado.", empty: "Não detectamos fala clara. Ouça a gravação antes de tentar novamente.", size: "O áudio ultrapassa 2 minutos ou 3 MB. Você pode baixá-lo.", unsupported: "Este navegador não permite gravar e transcrever aqui. Você pode usar o ditado do teclado.", limit: "Máximo 2 minutos", microphone: "Microfone", player: "Revisar áudio gravado",
  },
};
