import { createHash, randomBytes, randomUUID } from "node:crypto";
export type Network="stellar-testnet"|"base-sepolia"|"avalanche-fuji"|"offchain-demo";export type Kind="finance"|"reservation"|"task"|"travel"|"product"|"service";
export type Offer={id:string;merchant:string;title:string;description:string;kind:Kind;amount:number;currency:"USDC";network:Network;availability:"demo"|"testnet"|"partner_pending"};
export type Intent={id:string;offerId:string;actorId:string;amount:number;currency:"USDC";network:Network;status:"prepared"|"policy_approved"|"authorized"|"executed"|"rejected";idempotencyKey:string;createdAt:string;expiresAt:string;policy?:{allowed:boolean;reasons:string[];evaluatedAt:string;policyVersion:"demo-v1"};authorization?:{token:string;authorizedAt:string;expiresAt:string};receipt?:Receipt};
export type Receipt={id:string;intentId:string;status:"simulated-settled";network:Network;amount:number;currency:"USDC";transactionRef:string;executedAt:string;fulfillment:"pending-partner-confirmation";replayed:boolean};
export const offers:Offer[]=[
{id:"defindex-yield-demo",merchant:"DeFindex",title:"Prepare a 20 USDC testnet vault deposit",description:"Policy, authorization and a durable receipt. No funds move yet.",kind:"finance",amount:20,currency:"USDC",network:"stellar-testnet",availability:"testnet"},
{id:"innovation-day-pass",merchant:"UNBLCK / Tellus Hub",title:"Reserve an innovation day pass",description:"Prepare a workspace reservation and wait for partner confirmation.",kind:"reservation",amount:15,currency:"USDC",network:"offchain-demo",availability:"partner_pending"},
{id:"travala-search",merchant:"Travala",title:"Prepare an accommodation search",description:"Search and preparation only; paid booking remains disabled.",kind:"travel",amount:0,currency:"USDC",network:"offchain-demo",availability:"demo"}];
export interface IntentStore{get(id:string):Intent|undefined;getByKey(key:string):Intent|undefined;save(intent:Intent):void}
export class InMemoryIntentStore implements IntentStore{private intents=new Map<string,Intent>();private keys=new Map<string,string>();get(id:string){return this.intents.get(id)}getByKey(key:string){const id=this.keys.get(key);return id?this.intents.get(id):undefined}save(i:Intent){this.intents.set(i.id,i);this.keys.set(i.idempotencyKey,i.id)}}
export class CommerceService{constructor(private store:IntentStore){}searchOffers(query="",kind?:Kind){const q=query.toLowerCase().trim();return offers.filter(o=>(!q||`${o.title} ${o.description} ${o.merchant}`.toLowerCase().includes(q))&&(!kind||o.kind===kind))}getOffer(id:string){const o=offers.find(x=>x.id===id);if(!o)throw Error("offer_not_found");return o}createIntent(input:{offerId:string;actorId:string;idempotencyKey:string;amount?:number}){const old=this.store.getByKey(input.idempotencyKey);if(old)return{intent:old,replayed:true};const o=this.getOffer(input.offerId),now=Date.now(),i:Intent={id:`int_${randomUUID()}`,offerId:o.id,actorId:input.actorId,amount:input.amount??o.amount,currency:o.currency,network:o.network,status:"prepared",idempotencyKey:input.idempotencyKey,createdAt:new Date(now).toISOString(),expiresAt:new Date(now+900000).toISOString()};this.store.save(i);return{intent:i,replayed:false}}evaluatePolicy(id:string){const i=this.require(id),reasons:string[]=[];if(Date.parse(i.expiresAt)<=Date.now())reasons.push("intent_expired");if(i.amount<0)reasons.push("invalid_amount");if(i.amount>100)reasons.push("demo_limit_exceeded");i.policy={allowed:!reasons.length,reasons:reasons.length?reasons:["within_demo_limit","supported_test_network"],evaluatedAt:new Date().toISOString(),policyVersion:"demo-v1"};i.status=i.policy.allowed?"policy_approved":"rejected";this.store.save(i);return i}authorize(id:string,confirmed:boolean){const i=this.require(id);if(!confirmed)throw Error("explicit_confirmation_required");if(!i.policy?.allowed||i.status!=="policy_approved")throw Error("policy_approval_required");const now=Date.now();i.authorization={token:`auth_${randomBytes(24).toString("base64url")}`,authorizedAt:new Date(now).toISOString(),expiresAt:new Date(now+300000).toISOString()};i.status="authorized";this.store.save(i);return i}execute(id:string,token:string){const i=this.require(id);if(i.receipt)return{...i.receipt,replayed:true};if(i.status!=="authorized"||!i.authorization)throw Error("authorization_required");if(i.authorization.token!==token)throw Error("invalid_authorization");if(Date.parse(i.authorization.expiresAt)<=Date.now())throw Error("authorization_expired");const h=createHash("sha256").update(`${i.id}:${i.idempotencyKey}`).digest("hex"),r:Receipt={id:`rcpt_${h.slice(0,24)}`,intentId:i.id,status:"simulated-settled",network:i.network,amount:i.amount,currency:i.currency,transactionRef:`demo_${h}`,executedAt:new Date().toISOString(),fulfillment:"pending-partner-confirmation",replayed:false};i.receipt=r;i.status="executed";this.store.save(i);return r}getReceipt(id:string){return this.require(id).receipt??null}private require(id:string){const i=this.store.get(id);if(!i)throw Error("intent_not_found");return i}}
const g=globalThis as typeof globalThis&{__commerce?:CommerceService};export const commerce=g.__commerce??=new CommerceService(new InMemoryIntentStore());export function publicIntent(i:Intent){const{authorization,...safe}=i;return{...safe,authorization:authorization?{authorizedAt:authorization.authorizedAt,expiresAt:authorization.expiresAt}:undefined}}
