import{boolean,index,integer,jsonb,numeric,pgTable,text,timestamp,uniqueIndex}from"drizzle-orm/pg-core";
export const agentUsers=pgTable("agent_users",{id:text("id").primaryKey(),email:text("email"),status:text("status").notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),lastSeenAt:timestamp("last_seen_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_users_email_idx").on(t.email),index("agent_users_last_seen_idx").on(t.lastSeenAt)]);
export const agentWallets=pgTable("agent_wallets",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),address:text("address").notNull(),chainType:text("chain_type").notNull(),network:text("network").notNull(),status:text("status").notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_wallets_address_uidx").on(t.address),index("agent_wallets_user_idx").on(t.userId)]);
export const agentActivities=pgTable("agent_activities",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),eventType:text("event_type").notNull(),summary:text("summary").notNull(),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_activities_user_created_idx").on(t.userId,t.createdAt)]);
export const agentConversations=pgTable("agent_conversations",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),title:text("title").notNull().default("My agent"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_conversations_user_updated_idx").on(t.userId,t.updatedAt)]);
export const agentMessages=pgTable("agent_messages",{id:text("id").primaryKey(),conversationId:text("conversation_id").notNull().references(()=>agentConversations.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),role:text("role").notNull(),content:text("content").notNull(),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_messages_conversation_created_idx").on(t.conversationId,t.createdAt),index("agent_messages_user_idx").on(t.userId)]);
export const agentConnectionInterests=pgTable("agent_connection_interests",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),connectionName:text("connection_name").notNull(),status:text("status").notNull().default("exploring"),lastMessage:text("last_message"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_connection_interests_user_name_uidx").on(t.userId,t.connectionName),index("agent_connection_interests_status_idx").on(t.status)]);
export const commerceIntents=pgTable("commerce_intents",{id:text("id").primaryKey(),offerId:text("offer_id").notNull(),actorId:text("actor_id").notNull(),amount:numeric("amount",{precision:20,scale:7}).notNull(),currency:text("currency").notNull(),network:text("network").notNull(),status:text("status").notNull(),idempotencyKey:text("idempotency_key").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("commerce_intents_idempotency_key_uidx").on(t.idempotencyKey),index("commerce_intents_actor_idx").on(t.actorId)]);
export const policyDecisions=pgTable("policy_decisions",{id:text("id").primaryKey(),intentId:text("intent_id").notNull().references(()=>commerceIntents.id),allowed:boolean("allowed").notNull(),reasons:jsonb("reasons").$type<string[]>().notNull(),policyVersion:text("policy_version").notNull(),evaluatedAt:timestamp("evaluated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("policy_decisions_intent_uidx").on(t.intentId)]);
export const authorizations=pgTable("authorizations",{id:text("id").primaryKey(),intentId:text("intent_id").notNull().references(()=>commerceIntents.id),tokenHash:text("token_hash").notNull(),authorizedAt:timestamp("authorized_at",{withTimezone:true}).notNull().defaultNow(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),revokedAt:timestamp("revoked_at",{withTimezone:true})},t=>[uniqueIndex("authorizations_intent_uidx").on(t.intentId),uniqueIndex("authorizations_token_hash_uidx").on(t.tokenHash)]);
export const receipts=pgTable("receipts",{id:text("id").primaryKey(),intentId:text("intent_id").notNull().references(()=>commerceIntents.id),status:text("status").notNull(),network:text("network").notNull(),amount:numeric("amount",{precision:20,scale:7}).notNull(),currency:text("currency").notNull(),transactionRef:text("transaction_ref").notNull(),executedAt:timestamp("executed_at",{withTimezone:true}).notNull().defaultNow(),fulfillment:text("fulfillment").notNull()},t=>[uniqueIndex("receipts_intent_uidx").on(t.intentId),uniqueIndex("receipts_transaction_ref_uidx").on(t.transactionRef)]);
export const auditEvents=pgTable("audit_events",{id:text("id").primaryKey(),intentId:text("intent_id").references(()=>commerceIntents.id),eventType:text("event_type").notNull(),actorId:text("actor_id"),payload:jsonb("payload").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("audit_events_intent_created_idx").on(t.intentId,t.createdAt)]);
export const waitlistSignups=pgTable("waitlist_signups",{id:text("id").primaryKey(),email:text("email").notNull(),role:text("role").notNull(),useCase:text("use_case").notNull(),country:text("country"),company:text("company"),source:text("source").notNull().default("website"),referral:text("referral"),consent:boolean("consent").notNull(),status:text("status").notNull().default("waiting"),priority:text("priority").notNull().default("normal"),notes:text("notes"),owner:text("owner"),tags:jsonb("tags").$type<string[]>().notNull().default([]),lastContactedAt:timestamp("last_contacted_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("waitlist_signups_email_uidx").on(t.email),index("waitlist_signups_role_idx").on(t.role),index("waitlist_signups_status_created_idx").on(t.status,t.createdAt),index("waitlist_signups_source_idx").on(t.source),index("waitlist_signups_priority_idx").on(t.priority)]);
export const waitlistActivities=pgTable("waitlist_activities",{id:text("id").primaryKey(),signupId:text("signup_id").notNull().references(()=>waitlistSignups.id,{onDelete:"cascade"}),eventType:text("event_type").notNull(),fromStatus:text("from_status"),toStatus:text("to_status"),note:text("note"),actor:text("actor").notNull().default("founder"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("waitlist_activities_signup_created_idx").on(t.signupId,t.createdAt)]);

export const agentExternalConnections=pgTable("agent_external_connections",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),provider:text("provider").notNull(),status:text("status").notNull().default("active"),accessTokenEncrypted:text("access_token_encrypted").notNull(),refreshTokenEncrypted:text("refresh_token_encrypted"),tokenExpiresAt:timestamp("token_expires_at",{withTimezone:true}),scopes:jsonb("scopes").$type<string[]>().notNull().default([]),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_external_connections_user_provider_uidx").on(t.userId,t.provider),index("agent_external_connections_status_idx").on(t.status)]);

export const agentOauthStates=pgTable("agent_oauth_states",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),provider:text("provider").notNull(),codeVerifierEncrypted:text("code_verifier_encrypted").notNull(),clientId:text("client_id").notNull(),clientSecretEncrypted:text("client_secret_encrypted"),authorizationEndpoint:text("authorization_endpoint").notNull(),tokenEndpoint:text("token_endpoint").notNull(),redirectUri:text("redirect_uri").notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_oauth_states_user_provider_idx").on(t.userId,t.provider),index("agent_oauth_states_expires_idx").on(t.expiresAt)]);
export const agentMarketWatchlist=pgTable("agent_market_watchlist",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),symbol:text("symbol").notNull(),source:text("source").notNull().default("coinmarketcap"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_market_watchlist_user_symbol_uidx").on(t.userId,t.symbol),index("agent_market_watchlist_user_idx").on(t.userId)]);

export const serviceProviders=pgTable("service_providers",{id:text("id").primaryKey(),slug:text("slug").notNull(),name:text("name").notNull(),contactEmail:text("contact_email"),status:text("status").notNull().default("active"),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("service_providers_slug_uidx").on(t.slug),index("service_providers_status_idx").on(t.status)]);
export const serviceOffers=pgTable("service_offers",{id:text("id").primaryKey(),providerId:text("provider_id").notNull().references(()=>serviceProviders.id,{onDelete:"cascade"}),externalId:text("external_id").notNull(),title:text("title").notNull(),description:text("description").notNull(),kind:text("kind").notNull(),amount:numeric("amount",{precision:20,scale:7}).notNull(),currency:text("currency").notNull(),network:text("network").notNull(),status:text("status").notNull().default("draft"),metadata:jsonb("metadata").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("service_offers_provider_external_uidx").on(t.providerId,t.externalId),index("service_offers_provider_status_idx").on(t.providerId,t.status)]);
export const mcpAccessTokens=pgTable("mcp_access_tokens",{id:text("id").primaryKey(),subjectType:text("subject_type").notNull(),subjectId:text("subject_id").notNull(),name:text("name").notNull(),tokenPrefix:text("token_prefix").notNull(),tokenHash:text("token_hash").notNull(),scopes:jsonb("scopes").$type<string[]>().notNull().default([]),status:text("status").notNull().default("active"),expiresAt:timestamp("expires_at",{withTimezone:true}),lastUsedAt:timestamp("last_used_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("mcp_access_tokens_hash_uidx").on(t.tokenHash),index("mcp_access_tokens_subject_idx").on(t.subjectType,t.subjectId),index("mcp_access_tokens_status_idx").on(t.status)]);


export const agentGatewayPlans=pgTable("agent_gateway_plans",{id:text("id").primaryKey(),actorId:text("actor_id").notNull(),apiVersion:text("api_version").notNull(),environment:text("environment").notNull(),capabilityId:text("capability_id").notNull(),status:text("status").notNull(),idempotencyKey:text("idempotency_key").notNull(),requestFingerprint:text("request_fingerprint").notNull(),parameters:jsonb("parameters").$type<Record<string,unknown>>().notNull().default({}),blockers:jsonb("blockers").$type<string[]>().notNull().default([]),safety:jsonb("safety").$type<Record<string,unknown>>().notNull(),approval:jsonb("approval").$type<Record<string,unknown>>().notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull()},t=>[uniqueIndex("agent_gateway_plans_actor_idempotency_uidx").on(t.actorId,t.idempotencyKey),index("agent_gateway_plans_actor_status_idx").on(t.actorId,t.status),index("agent_gateway_plans_expires_idx").on(t.expiresAt)]);
export const agentGatewayReceipts=pgTable("agent_gateway_receipts",{id:text("id").primaryKey(),planId:text("plan_id").notNull().references(()=>agentGatewayPlans.id,{onDelete:"cascade"}),actorId:text("actor_id").notNull(),capabilityId:text("capability_id").notNull(),network:text("network").notNull(),status:text("status").notNull(),transactionHash:text("transaction_hash"),evidence:jsonb("evidence").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_gateway_receipts_plan_uidx").on(t.planId),index("agent_gateway_receipts_actor_created_idx").on(t.actorId,t.createdAt),index("agent_gateway_receipts_status_idx").on(t.status)]);

export const agentStellarActions=pgTable("agent_stellar_actions",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),walletId:text("wallet_id").notNull(),walletAddress:text("wallet_address").notNull(),action:text("action").notNull(),asset:text("asset").notNull(),amount:numeric("amount",{precision:20,scale:7}).notNull(),status:text("status").notNull().default("prepared"),idempotencyKey:text("idempotency_key").notNull(),preparedXdr:text("prepared_xdr").notNull(),signedXdr:text("signed_xdr"),transactionHash:text("transaction_hash"),preview:jsonb("preview").$type<Record<string,unknown>>().notNull().default({}),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),error:text("error"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow(),confirmedAt:timestamp("confirmed_at",{withTimezone:true})},t=>[uniqueIndex("agent_stellar_actions_idempotency_uidx").on(t.idempotencyKey),uniqueIndex("agent_stellar_actions_tx_hash_uidx").on(t.transactionHash),index("agent_stellar_actions_user_created_idx").on(t.userId,t.createdAt),index("agent_stellar_actions_status_idx").on(t.status)]);

export const agentKnowledgeItems=pgTable("agent_knowledge_items",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),kind:text("kind").notNull(),title:text("title").notNull(),content:text("content").notNull(),source:text("source").notNull().default("chat"),scope:text("scope").notNull().default("personal"),sensitivity:text("sensitivity").notNull().default("standard"),status:text("status").notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_knowledge_user_kind_idx").on(t.userId,t.kind),index("agent_knowledge_user_status_idx").on(t.userId,t.status)]);
export const agentPolicies=pgTable("agent_policies",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),kind:text("kind").notNull(),label:text("label").notNull(),enforcement:text("enforcement").notNull().default("hard"),config:jsonb("config").$type<Record<string,unknown>>().notNull().default({}),source:text("source").notNull().default("chat"),status:text("status").notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_policies_user_kind_idx").on(t.userId,t.kind),index("agent_policies_user_status_idx").on(t.userId,t.status)]);
export const agentDecisionEvents=pgTable("agent_decision_events",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),actionType:text("action_type").notNull(),outcome:text("outcome").notNull(),reasonCodes:jsonb("reason_codes").$type<string[]>().notNull().default([]),explanation:jsonb("explanation").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_decisions_user_created_idx").on(t.userId,t.createdAt),index("agent_decisions_outcome_idx").on(t.outcome)]);

export const agentX402Payments=pgTable("agent_x402_payments",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),walletId:text("wallet_id").notNull(),walletAddress:text("wallet_address").notNull(),resourceUrl:text("resource_url").notNull(),network:text("network").notNull(),assetContract:text("asset_contract").notNull(),payTo:text("pay_to").notNull(),amountAtomic:numeric("amount_atomic",{precision:30,scale:0}).notNull(),amountDisplay:numeric("amount_display",{precision:20,scale:7}).notNull(),status:text("status").notNull().default("prepared"),idempotencyKey:text("idempotency_key").notNull(),paymentRequired:jsonb("payment_required").$type<Record<string,unknown>>().notNull(),settlement:jsonb("settlement").$type<Record<string,unknown>>(),transactionHash:text("transaction_hash"),resourcePreview:text("resource_preview"),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),error:text("error"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow(),confirmedAt:timestamp("confirmed_at",{withTimezone:true})},t=>[uniqueIndex("agent_x402_payments_idempotency_uidx").on(t.idempotencyKey),uniqueIndex("agent_x402_payments_tx_hash_uidx").on(t.transactionHash),index("agent_x402_payments_user_created_idx").on(t.userId,t.createdAt),index("agent_x402_payments_status_idx").on(t.status)]);
export const agentX402Events=pgTable("agent_x402_events",{id:text("id").primaryKey(),paymentId:text("payment_id").notNull().references(()=>agentX402Payments.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),eventType:text("event_type").notNull(),payload:jsonb("payload").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_x402_events_payment_created_idx").on(t.paymentId,t.createdAt),index("agent_x402_events_user_created_idx").on(t.userId,t.createdAt),index("agent_x402_events_type_idx").on(t.eventType)]);

export const agentEvmCalls=pgTable("agent_evm_calls",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),walletAddress:text("wallet_address").notNull(),network:text("network").notNull(),actionId:text("action_id").notNull(),stepIndex:integer("step_index").notNull(),idempotencyKey:text("idempotency_key").notNull(),kind:text("kind").notNull(),status:text("status").notNull().default("prepared"),preview:jsonb("preview").$type<Record<string,unknown>>().notNull().default({}),signature:text("signature"),transactionHash:text("transaction_hash"),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),error:text("error"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow(),confirmedAt:timestamp("confirmed_at",{withTimezone:true})},t=>[uniqueIndex("agent_evm_calls_idempotency_uidx").on(t.idempotencyKey),uniqueIndex("agent_evm_calls_action_step_uidx").on(t.actionId,t.stepIndex),index("agent_evm_calls_user_created_idx").on(t.userId,t.createdAt),index("agent_evm_calls_status_idx").on(t.status)]);

export const agentTestnetFaucetClaims=pgTable("agent_testnet_faucet_claims",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),walletAddress:text("wallet_address").notNull(),asset:text("asset").notNull(),amount:numeric("amount",{precision:20,scale:7}).notNull(),claimWindow:text("claim_window").notNull(),status:text("status").notNull().default("pending"),transactionHash:text("transaction_hash"),error:text("error"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_testnet_faucet_claims_user_asset_window_uidx").on(t.userId,t.asset,t.claimWindow),uniqueIndex("agent_testnet_faucet_claims_tx_hash_uidx").on(t.transactionHash),index("agent_testnet_faucet_claims_status_idx").on(t.status)]);

export const agentWorkflows=pgTable("agent_workflows",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),conversationId:text("conversation_id").notNull().references(()=>agentConversations.id,{onDelete:"cascade"}),connectorId:text("connector_id").notNull(),capability:text("capability").notNull(),operation:text("operation").notNull(),risk:text("risk").notNull(),status:text("status").notNull().default("planning"),actionDigest:text("action_digest"),idempotencyKey:text("idempotency_key").notNull(),state:jsonb("state").$type<Record<string,unknown>>().notNull(),version:integer("version").notNull().default(0),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("agent_workflows_idempotency_uidx").on(t.idempotencyKey),index("agent_workflows_user_updated_idx").on(t.userId,t.updatedAt),index("agent_workflows_status_idx").on(t.status)]);
export const agentWorkflowEvents=pgTable("agent_workflow_events",{id:text("id").primaryKey(),workflowId:text("workflow_id").notNull().references(()=>agentWorkflows.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),node:text("node").notNull(),status:text("status").notNull(),version:integer("version").notNull(),payload:jsonb("payload").$type<Record<string,unknown>>().notNull().default({}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_workflow_events_workflow_created_idx").on(t.workflowId,t.createdAt),index("agent_workflow_events_user_created_idx").on(t.userId,t.createdAt)]);

// Telegram bridge: maps a Telegram chat identity to an agent user (Privy id when linked, otherwise a standalone tg:<id> user).
export const telegramLinks=pgTable("telegram_links",{telegramUserId:text("telegram_user_id").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),chatId:text("chat_id"),username:text("username"),language:text("language").notNull().default("en"),status:text("status").notNull().default("active"),linkedAt:timestamp("linked_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("telegram_links_user_idx").on(t.userId)]);
// One-time codes generated in the web app to bind a Telegram identity to an existing Privy account (Connect-code pattern).
export const telegramLinkCodes=pgTable("telegram_link_codes",{code:text("code").primaryKey(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),usedAt:timestamp("used_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("telegram_link_codes_user_idx").on(t.userId),index("telegram_link_codes_expires_idx").on(t.expiresAt)]);
// Short callback ids for inline buttons: Telegram caps callback_data at 64 bytes, so the full agent message (e.g. a long UNBLCK_CONFIRM token) is stored here and referenced by a short id.
export const telegramPendingActions=pgTable("telegram_pending_actions",{id:text("id").primaryKey(),telegramUserId:text("telegram_user_id").notNull(),userId:text("user_id").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),message:text("message").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("telegram_pending_actions_tg_idx").on(t.telegramUserId)]);

export const integrationRecommendations=pgTable("integration_recommendations",{id:text("id").primaryKey(),integrationName:text("integration_name").notNull(),email:text("email").notNull(),useCase:text("use_case"),locale:text("locale").notNull().default("en"),source:text("source").notNull().default("landing"),status:text("status").notNull().default("new"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("integration_recommendations_email_name_uidx").on(t.email,t.integrationName),index("integration_recommendations_status_created_idx").on(t.status,t.createdAt),index("integration_recommendations_name_idx").on(t.integrationName)]);

export const agentGatewayRateLimits=pgTable("agent_gateway_rate_limits",{key:text("key").primaryKey(),scope:text("scope").notNull(),subjectPseudonym:text("subject_pseudonym").notNull(),windowStartedAt:timestamp("window_started_at",{withTimezone:true}).notNull(),windowEndsAt:timestamp("window_ends_at",{withTimezone:true}).notNull(),requestCount:integer("request_count").notNull().default(1),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_gateway_rate_limits_subject_scope_idx").on(t.subjectPseudonym,t.scope),index("agent_gateway_rate_limits_expires_idx").on(t.windowEndsAt)]);
export const agentGatewayAuditEvents=pgTable("agent_gateway_audit_events",{id:text("id").primaryKey(),requestId:text("request_id").notNull(),actorPseudonym:text("actor_pseudonym"),tokenPseudonym:text("token_pseudonym"),route:text("route").notNull(),tool:text("tool"),outcome:text("outcome").notNull(),status:integer("status").notNull(),latencyMs:integer("latency_ms").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[index("agent_gateway_audit_events_created_idx").on(t.createdAt),index("agent_gateway_audit_events_route_outcome_idx").on(t.route,t.outcome),index("agent_gateway_audit_events_actor_created_idx").on(t.actorPseudonym,t.createdAt)]);

export const oauthSubjectLinks=pgTable("oauth_subject_links",{id:text("id").primaryKey(),issuer:text("issuer").notNull(),subject:text("subject").notNull(),privyDid:text("privy_did").notNull().references(()=>agentUsers.id,{onDelete:"cascade"}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("oauth_subject_links_issuer_subject_uidx").on(t.issuer,t.subject),uniqueIndex("oauth_subject_links_issuer_privy_uidx").on(t.issuer,t.privyDid),index("oauth_subject_links_privy_idx").on(t.privyDid)]);
