import {
  listAvalancheCapabilities,
  type AvalancheCapability,
} from "@/app/avalanche/capability-registry";
import {
  GATEWAY_API_VERSION,
  type GatewayCapability,
} from "@/app/agent-gateway/types";

type StaticCapability = Omit<GatewayCapability, "version" | "execution" | "requiresApproval">;

const staticCapabilities: readonly StaticCapability[] = [
  {
    id: "stellar.wallet.status",
    title: "Inspect the user's Stellar wallet",
    description: "Return the user-owned Stellar Testnet address and verified balances.",
    provider: "Privy + Stellar Horizon",
    category: "wallet",
    status: "live",
    operation: "read",
    network: "stellar:testnet",
    approval: "none",
    requirements: ["privy_session", "stellar_wallet"],
    evidence: "Privy ownership and Stellar Testnet Horizon balance reads are implemented.",
    nextAction: "Ask Carmelita to show the Stellar Testnet wallet and balances.",
  },
  {
    id: "stellar.wallet.friendbot_fund",
    title: "Fund a Stellar Testnet wallet",
    description: "Activate a user-owned Stellar Testnet account with Friendbot funds.",
    provider: "Stellar Friendbot",
    category: "wallet",
    status: "live",
    operation: "financial",
    network: "stellar:testnet",
    approval: "user_confirmation",
    requirements: ["privy_session", "stellar_wallet"],
    evidence: "The authenticated, idempotent Friendbot flow and on-chain verification are implemented.",
    nextAction: "Confirm activation from Carmelita; never share a wallet secret.",
  },
  {
    id: "stellar.usdc.trustline",
    title: "Create the Testnet USDC trustline",
    description: "Prepare the exact Stellar Testnet USDC trustline for user approval.",
    provider: "Stellar + Privy",
    category: "payments",
    status: "live",
    operation: "financial",
    network: "stellar:testnet",
    approval: "privy_single",
    requirements: ["privy_session", "stellar_wallet", "stellar_xlm"],
    evidence: "Unsigned preparation, client signature attachment and submitted-transaction verification are implemented.",
    nextAction: "Prepare in Carmelita and explicitly approve the exact transaction with Privy.",
  },
  {
    id: "stellar.x402.report.purchase",
    title: "Purchase an x402 Testnet resource",
    description: "Pay an x402 challenge with Stellar Testnet USDC and return a replay-safe receipt.",
    provider: "Stellar x402",
    category: "payments",
    status: "live",
    operation: "financial",
    network: "stellar:testnet",
    approval: "privy_single",
    requirements: ["privy_session", "stellar_wallet", "stellar_usdc_trustline", "stellar_usdc"],
    evidence: "Real Testnet settlement, exact debit verification and zero-debit replay are covered by acceptance evidence.",
    nextAction: "Open Carmelita to approve a fresh 0.01 USDC Testnet purchase.",
  },
  {
    id: "stellar.defindex.deposit_xlm",
    title: "Deposit XLM into a DeFindex Testnet vault",
    description: "Prepare, sign through Privy and verify an XLM vault deposit on Stellar Testnet.",
    provider: "DeFindex",
    category: "defi",
    status: "live",
    operation: "financial",
    network: "stellar:testnet",
    approval: "privy_single",
    requirements: ["privy_session", "stellar_wallet", "stellar_xlm"],
    evidence: "The route persists unsigned intent state, validates the exact signature and verifies the submitted transaction.",
    nextAction: "Prepare a small XLM deposit inside Carmelita and approve it with Privy.",
  },
  {
    id: "stellar.defindex.deposit_usdc",
    title: "Deposit USDC into a DeFindex Testnet vault",
    description: "Prepare a USDC vault deposit after the exact Testnet trustline and balance are verified.",
    provider: "DeFindex",
    category: "defi",
    status: "ready_to_test",
    operation: "financial",
    network: "stellar:testnet",
    approval: "privy_single",
    requirements: ["privy_session", "stellar_wallet", "stellar_xlm", "stellar_usdc_trustline", "stellar_usdc"],
    evidence: "Preparation, signing and receipt checks are implemented; a fresh-user end-to-end USDC vault acceptance is still required.",
    nextAction: "Run one fresh-user Testnet USDC deposit and retain the verified receipt.",
  },
  {
    id: "stellar.soroswap.swap",
    title: "Swap XLM and USDC through Soroswap",
    description: "Quote and prepare a Stellar Testnet swap for explicit Privy approval.",
    provider: "Soroswap",
    category: "trading",
    status: "planned",
    operation: "financial",
    network: "stellar:testnet",
    approval: "privy_single",
    requirements: ["privy_session", "stellar_wallet", "soroswap_api", "source_balance"],
    evidence: "The local adapter is implemented, but the upstream Testnet path is not currently accepted as operational evidence.",
    nextAction: "Revalidate Soroswap Testnet upstream before exposing preparation to external agents.",
  },
  {
    id: "offchain.travala.hotel_search",
    title: "Search Travala hotels",
    description: "Search future hotel availability without booking or charging the user.",
    provider: "Travala",
    category: "travel",
    status: "ready_to_test",
    operation: "read",
    network: "offchain:testnet",
    approval: "none",
    requirements: ["privy_session"],
    evidence: "A bounded, authenticated search adapter with timeout and upstream-error handling is implemented.",
    nextAction: "Run one dated hotel search; booking and payment remain disabled.",
  },
  {
    id: "offchain.unblck.hub_state",
    title: "Read UNBLCK hub availability",
    description: "Read linked-user credits, bookings and available hub days.",
    provider: "UNBLCK",
    category: "reservations",
    status: "live",
    operation: "read",
    network: "offchain:testnet",
    approval: "none",
    requirements: ["privy_session", "unblck_linked_identity"],
    evidence: "The partner API contract and linked-user state flow are implemented and tested.",
    nextAction: "Link an identity and ask Carmelita for current availability.",
  },
  {
    id: "offchain.unblck.book",
    title: "Book an UNBLCK hub day",
    description: "Prepare a dated hub check-in that requires explicit user confirmation.",
    provider: "UNBLCK",
    category: "reservations",
    status: "live",
    operation: "prepare",
    network: "offchain:testnet",
    approval: "user_confirmation",
    requirements: ["privy_session", "unblck_linked_identity", "unblck_credit"],
    evidence: "Partner booking and cancellation contracts exist; UNBLCK remains the source of truth.",
    nextAction: "Review the exact date in Carmelita before confirming the partner call.",
  },
  {
    id: "offchain.market.quote",
    title: "Read cryptocurrency market prices",
    description: "Read a bounded market quote with CoinGecko primary and CoinMarketCap fallback.",
    provider: "CoinGecko + CoinMarketCap",
    category: "market_data",
    status: "live",
    operation: "read",
    network: "offchain:testnet",
    approval: "none",
    requirements: ["privy_session"],
    evidence: "Read-only adapters validate supported symbols, response shape and upstream failures.",
    nextAction: "Ask Carmelita for a supported asset quote.",
  },
  {
    id: "offchain.notion.search",
    title: "Search the user's Notion workspace",
    description: "Search the user's own Notion connection through the official remote MCP.",
    provider: "Notion MCP",
    category: "knowledge",
    status: "live",
    operation: "read",
    network: "offchain:testnet",
    approval: "none",
    requirements: ["privy_session", "notion_oauth"],
    evidence: "Per-user OAuth token retrieval and bounded MCP search are implemented.",
    nextAction: "Connect Notion in Carmelita, then run a scoped workspace search.",
  },
] as const;

function executionFor(operation: GatewayCapability["operation"]) {
  return {
    exposedByGateway: false,
    mode: operation === "read" ? "read_only" : "prepare_then_approve",
  } as const;
}

function fromAvalanche(capability: AvalancheCapability & { category: string }): GatewayCapability {
  return {
    id: capability.id,
    version: GATEWAY_API_VERSION,
    title: capability.title,
    description: capability.description,
    provider: capability.provider,
    category: capability.category,
    status: capability.status,
    operation: capability.operation,
    network: capability.network,
    approval: capability.approval,
    requiresApproval: capability.approval !== "none",
    requirements: capability.requires,
    evidence: capability.evidence,
    nextAction: capability.nextAction,
    execution: executionFor(capability.operation),
  };
}

export function listGatewayCapabilities(): GatewayCapability[] {
  return [
    ...staticCapabilities.map((capability) => ({
      ...capability,
      requiresApproval: capability.approval !== "none",
      version: GATEWAY_API_VERSION,
      execution: executionFor(capability.operation),
    })),
    ...listAvalancheCapabilities().map(fromAvalanche),
  ];
}

export function getGatewayCapability(id: string) {
  const capability = listGatewayCapabilities().find((item) => item.id === id);
  if (!capability) throw new Error("gateway_capability_not_found");
  return capability;
}
